Goodies
juxuanu/worldcoo-kiosk pull request #1
Opened 2024-01-20 13:29 UTC by romulovalez

- Change font for a monospaced one to avoid font shift
- Add animation to number
- Add confetti at every 10.000 euros

2024-01-23 16:28 UTC, juxuanu requested changes
Creo que le falta pasar un `pnpm prettier -w .`

2024-01-23 16:28 UTC, juxuanu commented on src/pages/index.astro
> +    <div class="mt-auto h-[200px] w-full">
Estaría bien no hardcodear píxeles. ¿Usamos dvh aquí también? O aunque sean rem.
Si crees que píxeles mejor, soy todo oidos.

2024-01-23 16:28 UTC, juxuanu commented on src/pages/index.astro
> +  .odometer-numbers {
Vaya hack, haha. Pero bueno, si no hay alternativa...

2024-01-23 16:28 UTC, juxuanu commented on src/pages/index.astro
> +              resolve(void 0);
¿Por qué añades `void 0`?

2024-01-23 16:30 UTC, juxuanu commented
Por cierto, creo que sería mejor un gráfico de barras. Tiene más sentido. La cantidad de donaciones es algo discreto, no continuo.

2024-01-23 16:32 UTC, juxuanu commented
Ah, y antes se veía bien desde móbil :-(

![image](https://github.com/juxuanu/worldcoo-kiosk/assets/24759034/49a7b1c7-66c1-4fd2-bf80-d7a3f2a5aa85)

2024-01-23 16:49 UTC, romulovalez commented
Sí, he hecho unos cambios al vuelo con Aureli al lado xd, luego refino

2024-01-25 08:48 UTC, romulovalez commented on src/pages/index.astro
> +              resolve(void 0);
Me lo pedía tsc, lo he cambiado a undefined que es más claro

2024-01-25 21:38 UTC, merged